name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

env:
  Configuration: Release

concurrency:
  group: Publish
  cancel-in-progress: true

jobs:
  pack:
    name: Build, Test, Pack on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '11.0.x'
        source-url: https://nuget.pkg.github.com/TSSArt/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.XTATE_GITHUB_TOKEN }}
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.5.0
      with:
        versionSpec: '6.5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v4.5.0
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ env.Configuration }} --no-restore -p:Version=${{ env.fullSemVer }}
    - name: Test
      run: dotnet test --configuration ${{ env.Configuration }} --no-build -p:SkipNetFrameworkTests=true
    - name: Pack
      run: dotnet pack --configuration ${{ env.Configuration }} --no-build -p:PackageVersion=${{ env.fullSemVer }} --include-symbols -p:SymbolPackageFormat=snupkg -o bin/packages
    - name: Upload Packages
      uses: actions/upload-artifact@v7
      with:
        name: packages
        path: |
          bin/packages/*.nupkg
          bin/packages/*.snupkg

  test-windows:
    name: Build, Test on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '11.0.x'
        source-url: https://nuget.pkg.github.com/TSSArt/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.XTATE_GITHUB_TOKEN }}
    - name: Test
      run: dotnet test --configuration ${{ env.Configuration }}

  publish:
    name: Publish Packages
    needs:
      - pack
      - test-windows
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
    - name: Download Packages
      uses: actions/download-artifact@v8
      with:
        name: packages
        path: bin/packages
    - name: Publish to NuGet.org
      run: dotnet nuget push bin/packages/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_ORG_TOKEN }}
    - name: Publish to GitHub
      run: dotnet nuget push bin/packages/*.nupkg -s https://nuget.pkg.github.com/TSSArt/index.json -k ${{ secrets.XTATE_GITHUB_TOKEN }}
